### ISSUE TITLE
Crash on /multitexts/

### ISSUE THREAD

**Issue by jeffkinnison** [tesserae/apitess#54]
When accessing the /multitexts/ endpoint, this traceback is returned.

```
Traceback (most recent call last):
    File "/var/www/tesserae_flask/lib/python3.6/site-packages/tesserae/utils/multitext.py", line 104, in _run_multitext
        unit_type, texts)
    File "/var/www/tesserae_flask/lib/python3.6/site-packages/tesserae/utils/multitext.py", line 505, in multitext_search
        feature_type, bigram_indices)
    File "/var/www/tesserae_flask/lib/python3.6/site-packages/tesserae/utils/multitext.py", line 444, in lookup_bigrams
        'word1=? and word2=?', bigram)]
    sqlite3.OperationalError: no such table: bigrams
```

It looks like the bigrams table isn't found--maybe something got jumbled in a maintenance op or redeploy?

To reproduce, run a standard multitext search.

**Comment by jeffkinnison** [comment]
Seems to have been fixed by re-ingesting the texts.
